build:
  image: index.shurenyun.com/solo:on-build
  commands:
    - mvn install
publish:
  docker:
    email: wtzhou@dataman-inc.com
    repo: shurenyun/solo
    storage_driver: devicemapper
    tag: $$COMMIT
