build:
  image: demoregistry.dataman-inc.com:5000/csdpub/solo:onbuild
  commands:
    - mvn install
publish:
  docker:
    email: wtzhou@dataman-inc.com
    repo: shurenyun/solo
    storage_driver: devicemapper
    tag: $$COMMIT
